FROM python:3

RUN pip install pytest
RUN pip install hypothesis

RUN mkdir dsbuild
COPY dotscience ./dsbuild/dotscience
COPY setup.py ./dsbuild
COPY README.md ./dsbuild
COPY LICENSE ./dsbuild

COPY .git ./dsbuild/.git
COPY .gitattributes ./dsbuild
COPY setup.cfg ./dsbuild
COPY MANIFEST.in ./dsbuild
COPY versioneer.py ./dsbuild
