FROM python:3

RUN mkdir dsbuild
COPY dotscience ./dsbuild/dotscience
COPY setup.py ./dsbuild
COPY README.md ./dsbuild
COPY LICENSE ./dsbuild
COPY MANIFEST.in ./dsbuild
COPY versioneer.py ./dsbuild
COPY setup.cfg ./dsbuild
COPY .gitattributes ./dsbuild